# These are supported funding model platforms

github: [Huibean]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/ublox.js
custom: # Replace with a single custom sponsorship URL
